# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-08 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='review',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
